version: "3.9"

services:
  <your-name>message-api:
    build: ./message-api
    container_name: <your-name>message-api
    ports:
      - "8081:5001"
    networks:
      - appnet

  <your-name>web-app:
    build: 
    container_name: 
    ports:
      
    depends_on:
      
    networks:
      

networks:
  appnet:
    driver: bridge