services:
  zacmessage-api:
    build: ./message-api
    container_name: zacmessage-api
    ports:
      - "8081:5001"
    networks:
      - appnet

  zacweb-app:
    build: ./web-app
    container_name: zacweb-app
    ports:
      - "8080:5000"
    depends_on:
      - zacmessage-api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge